// Generated by Xata Codegen 0.26.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "listings",
    columns: [
      { name: "name", type: "string" },
      { name: "email", type: "email" },
      { name: "description", type: "text" },
      { name: "price", type: "int" },
      { name: "thumbnail", type: "file" },
      { name: "userId", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Listings = InferredTypes["listings"];
export type ListingsRecord = Listings & XataRecord;

export type DatabaseSchema = {
  listings: ListingsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Guillaume-Bibeau-laviolette-s-workspace-uueint.us-east-1.xata.sh/db/sideyard",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
